const flowers = [
  // --- COMMON ---
  { name:"Daisy", rarity:"common", waters:15, cost:50, quote:"Happiness blooms here.", fact:"Daisies are edible and often used in salads.", seedbag:"assets/seedbags/daisy-seedbag.png", seedcard:"assets/seedjournal/daisy-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-daisy.png"},
  { name:"Marigold", rarity:"common", waters:20, cost:75, quote:"Bright days ahead.", fact:"Marigolds repel certain garden pests naturally.", seedbag:"assets/seedbags/marigold-seedbag.png", seedcard:"assets/seedjournal/marigold-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-marigold.png"},
  { name:"Pansies", rarity:"common", waters:25, cost:100, quote:"Colorful hearts.", fact:"Pansies symbolize love in the language of flowers.", seedbag:"assets/seedbags/pansies-seedbag.png", seedcard:"assets/seedjournal/pansies-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-pansies.png"},
  { name:"Nasturtium", rarity:"common", waters:30, cost:125, quote:"Spicy little joys.", fact:"Nasturtium leaves and flowers are edible with a peppery taste.", seedbag:"assets/seedbags/nasturtium-seedbag.png", seedcard:"assets/seedjournal/nasturtium-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-nasturtium.png"},
  { name:"Geranium", rarity:"common", waters:35, cost:150, quote:"Blushing blooms.", fact:"Geraniums are often used for their fragrant oils.", seedbag:"assets/seedbags/geranium-seedbag.png", seedcard:"assets/seedjournal/geranium-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-geranium.png"},
  { name:"Begonia", rarity:"common", waters:40, cost:175, quote:"Gentle elegance.", fact:"Begonias can bloom indoors year-round.", seedbag:"assets/seedbags/begonia-seedbag.png", seedcard:"assets/seedjournal/begonia-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-begonia.png"},
  { name:"Sunflowers", rarity:"common", waters:45, cost:200, quote:"Follow the sun.", fact:"Sunflowers can grow to over 10 feet tall.", seedbag:"assets/seedbags/sunflowers-seedbag.png", seedcard:"assets/seedjournal/sunflowers-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-sunflowers.png"},
  { name:"Cosmos", rarity:"common", waters:50, cost:225, quote:"Delicate dreams.", fact:"Cosmos attract butterflies to the garden.", seedbag:"assets/seedbags/cosmos-seedbag.png", seedcard:"assets/seedjournal/cosmos-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-cosmos.png"},

  // --- UNCOMMON ---
  { name:"Bluebells", rarity:"uncommon", waters:55, cost:300, quote:"Whispering woods.", fact:"Bluebells are native to Europe and bloom in spring.", seedbag:"assets/seedbags/bluebells-seedbag.png", seedcard:"assets/seedjournal/bluebells-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-bluebells.png"},
  { name:"Snapdragons", rarity:"uncommon", waters:60, cost:350, quote:"Playful blooms.", fact:"Snapdragons can ‘snap’ open when squeezed.", seedbag:"assets/seedbags/snapdragons-seedbag.png", seedcard:"assets/seedjournal/snapdragons-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-snapdragons.png"},
  { name:"Morning Glory", rarity:"uncommon", waters:65, cost:400, quote:"New day rising.", fact:"Morning Glories open in the morning and close at night.", seedbag:"assets/seedbags/morningglory-seedbag.png", seedcard:"assets/seedjournal/morningglory-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-morningglory.png"},
  { name:"Tulips", rarity:"uncommon", waters:70, cost:450, quote:"Graceful elegance.", fact:"Tulips were once more valuable than gold in Holland.", seedbag:"assets/seedbags/tulips-seedbag.png", seedcard:"assets/seedjournal/tulips-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-tulips.png"},
  { name:"Freesia", rarity:"uncommon", waters:75, cost:500, quote:"Scent of joy.", fact:"Freesias are known for their sweet fragrance.", seedbag:"assets/seedbags/freesia-seedbag.png", seedcard:"assets/seedjournal/freesia-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-freesia.png"},
  { name:"Anemone", rarity:"uncommon", waters:80, cost:550, quote:"Gentle whispers.", fact:"Anemones are named after the Greek word for wind.", seedbag:"assets/seedbags/anemone-seedbag.png", seedcard:"assets/seedjournal/anemone-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-anemone.png"},
  { name:"Lavender", rarity:"uncommon", waters:90, cost:600, quote:"Peace in purple.", fact:"Lavender is used for calming essential oils.", seedbag:"assets/seedbags/lavender-seedbag.png", seedcard:"assets/seedjournal/lavender-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-lavender.png"},
  { name:"Daffodils", rarity:"uncommon", waters:100, cost:650, quote:"Rebirth and renewal.", fact:"Daffodils symbolize new beginnings in spring.", seedbag:"assets/seedbags/daffodils-seedbag.png", seedcard:"assets/seedjournal/daffodils-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-daffodils.png"},

  // --- RARE ---
  { name:"Cherry Blossom", rarity:"rare", waters:90, cost:800, quote:"Ephemeral beauty.", fact:"Cherry blossoms bloom for only a few weeks each year.", seedbag:"assets/seedbags/cherryblossom-seedbag.png", seedcard:"assets/seedjournal/cherryblossom-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-cherryblossom.png"},
  { name:"Lily", rarity:"rare", waters:100, cost:900, quote:"Purity and elegance.", fact:"Lilies come in over 100 species worldwide.", seedbag:"assets/seedbags/lily-seedbag.png", seedcard:"assets/seedjournal/lily-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-lily.png"},
  { name:"Rose", rarity:"rare", waters:110, cost:1000, quote:"Love’s emblem.", fact:"Roses have been cultivated for over 5000 years.", seedbag:"assets/seedbags/rose-seedbag.png", seedcard:"assets/seedjournal/rose-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-rose.png"},
  { name:"Dahlia", rarity:"rare", waters:120, cost:1100, quote:"Bold and bright.", fact:"Dahlias are native to Mexico.", seedbag:"assets/seedbags/dahlia-seedbag.png", seedcard:"assets/seedjournal/dahlia-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-dahlia.png"},
  { name:"Hibiscus", rarity:"rare", waters:130, cost:1200, quote:"Tropical beauty.", fact:"Hibiscus flowers are used to make herbal teas.", seedbag:"assets/seedbags/hibiscus-seedbag.png", seedcard:"assets/seedjournal/hibiscus-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-hibiscus.png"},
  { name:"Peonies", rarity:"rare", waters:140, cost:1300, quote:"Full blooms of luck.", fact:"Peonies can live over 100 years.", seedbag:"assets/seedbags/peonies-seedbag.png", seedcard:"assets/seedjournal/peonies-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-peonies.png"},
  { name:"Gardenia", rarity:"rare", waters:150, cost:1400, quote:"Fragrant whispers.", fact:"Gardenias are native to tropical regions of Africa and Asia.", seedbag:"assets/seedbags/gardenia-seedbag.png", seedcard:"assets/seedjournal/gardenia-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-gardenia.png"},
  { name:"Orchid", rarity:"rare", waters:160, cost:1500, quote:"Exotic elegance.", fact:"Orchids are one of the largest plant families with over 25,000 species.", seedbag:"assets/seedbags/orchid-seedbag.png", seedcard:"assets/seedjournal/orchid-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-orchid.png"},

  // --- EPIC SEASONAL ---
  { name:"Dandelion Summer", rarity:"epic", waters:150, cost:2000, quote:"Sunny cheer.", fact:"Dandelions are edible and great for pollinators.", seedbag:"assets/seedbags/dandelion-seedbag.png", seedcard:"assets/seedjournal/dandelion-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-dandelion.png"},
  { name:"Maple Sapling Fall", rarity:"epic", waters:165, cost:2200, quote:"Golden whispers.", fact:"Japanese maples have delicate leaves that turn bright red in fall.", seedbag:"assets/seedbags/maple-seedbag.png", seedcard:"assets/seedjournal/maple-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-maple.png"},
  { name:"Hellebore Winter", rarity:"epic", waters:180, cost:2400, quote:"Snow-kissed bloom.", fact:"Hellebores bloom in winter and are frost-hardy.", seedbag:"assets/seedbags/hellebore-seedbag.png", seedcard:"assets/seedjournal/hellebore-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-hellebore.png"},
  { name:"Iris Spring", rarity:"epic", waters:195, cost:2600, quote:"Fresh beginnings.", fact:"Irises symbolize hope and wisdom.", seedbag:"assets/seedbags/iris-seedbag.png", seedcard:"assets/seedjournal/iris-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-iris.png"},

  // --- LEGENDARY HOLIDAY ---
  { name:"Bleeding Hearts", rarity:"legendary", waters:210, cost:2800, quote:"Love blooms eternal.", fact:"Bleeding hearts are perennial shade plants.", seedbag:"assets/seedbags/bleedinghearts-seedbag.png", seedcard:"assets/seedjournal/bleedinghearts-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-bleedinghearts.png"},
  { name:"Shamrock", rarity:"legendary", waters:225, cost:3000, quote:"Luck is growing.", fact:"Shamrocks are associated with good fortune in Irish folklore.", seedbag:"assets/seedbags/shamrock-seedbag.png", seedcard:"assets/seedjournal/shamrock-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-shamrock.png"},
  { name:"Ipheion", rarity:"legendary", waters:250, cost:5000, quote:"Stars of summer nights.", fact:"Ipheion flowers are small, star-shaped spring bloomers.", seedbag:"assets/seedbags/ipheion-seedbag.png", seedcard:"assets/seedjournal/ipheion-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-ipheion.png"},
  { name:"Poinsettia", rarity:"legendary", waters:300, cost:5500, quote:"Festive cheer blooms.", fact:"Poinsettias are native to Mexico and bloom in winter.", seedbag:"assets/seedbags/poinsettia-seedbag.png", seedcard:"assets/seedjournal/poinsettia-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-poinsettia.png"},
  { name:"Tacca Bat", rarity:"legendary", waters:350, cost:6000, quote:"Spooky surprises grow here.", fact:"Tacca bat flowers are unique and resemble bats in flight.", seedbag:"assets/seedbags/taccabat-seedbag.png", seedcard:"assets/seedjournal/taccabat-seed.png", stages:["seedstage","sproutstage","midgrowth","matureflower"], vase:"assets/vase/vase-taccabat.png"}
];
    
